import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css"; // Commented out to avoid Tailwind conflicts as requested

import AddBootstrap from "./AddBootstrap";

export const metadata = {
  title: "NextJs and Bootstrap 5",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body >
        <AddBootstrap />
        {children}</body>
    </html>
  );
}